### ISSUE TITLE
Issues with mongoDB

### ISSUE THREAD

**Issue by leogmg** [guido-an/Nextjs-E-Commerce#11]
Hi Guido! How's it going? Great supporter here from Brazil, cheers.
Guido, I would like to test this code out, but I'm having issues with setting up my backend. 
Could you help me out? Maybe with your dotenv or mongoDB setup, since there are none in the readme.
As always, thanks for your help!

Best regards, Leonardo

**Comment by guido-an** [comment]
Hey Leonardo,

Sorry but I am reading this only now.

This is a project built few years ago just for learning purposes.

Anyway, now both frontend and backend should run correctly.

Just specify the PORT in the .env file (backend)
